language: rust
rust:
  - nightly
  - beta
  - stable

sudo: required

services:
  - docker

script:
  - docker -t rust-buster build .
  - docker run rust-buster -it --rm -v $(pwd):/opt/rust/src cargo build --release
