[package]
name = "gmime"
homepage = "https://github.com/vhdirk/gmime-rs"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]
keywords = ["gmime", "gtk-rs", "gnome"]
readme = "README.md"
license = "MIT"
version = "0.0.1"
exclude = [
    "gir-files/*",
]


[lib]
name = "gmime"

# [features]
# v1_31 = ["gmime-sys/v1_31"]
# v1_32 = ["v1_31", "gmime-sys/v1_32"]
# v1_32_4 = ["v1_32", "gmime-sys/v1_32_4"]
# v1_34 = ["v1_32_4", "gmime-sys/v1_34"]
# v1_36_7 = ["v1_34", "gmime-sys/v1_36_7"]
# v1_38 = ["v1_36_7", "gmime-sys/v1_38"]
# v1_42 = ["v1_38", "gmime-sys/v1_42"]

[dependencies]
libc = "0.2"
bitflags = "1.0"
lazy_static = "1.0"


[dependencies.gmime-sys]
version = "0.6.0"
path = "gmime-sys"

[dependencies.gio]
git = "https://github.com/gtk-rs/gio"
version = "^0.4.0"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "^0.5.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"
