[options]
girs_dir = "gir-files"
library = "GMime"
version = "3.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = false
min_cfg_version = "1.30"

generate = [
    "GMime.AddressType",
    "GMime.AutocryptHeaderList",
    "GMime.AutocryptPreferEncrypt",
    "GMime.Certificate",
    "GMime.CertificateList",
    "GMime.Charset",
    "GMime.CipherAlgo",
    "GMime.CryptoContext",
    "GMime.DataWrapper",
    "GMime.DecryptFlags",
    "GMime.DecryptResult",
    "GMime.Encoding",
    "GMime.EncryptFlags",
    "GMime.Filter",
    "GMime.FilterBasic",
    "GMime.FilterBest",
    "GMime.FilterBestFlags",
    "GMime.FilterCharset",
    "GMime.FilterChecksum",
    "GMime.FilterDos2Unix",
    "GMime.FilterEnriched",
    "GMime.FilterFrom",
    "GMime.FilterFromMode",
    "GMime.FilterGZip",
    "GMime.FilterGZipMode",
    "GMime.FilterHTML",
    "GMime.FilterOpenPGP",
    "GMime.FilterSmtpData",
    "GMime.FilterStrip",
    "GMime.FilterUnix2Dos",
    "GMime.FilterWindows",
    "GMime.FilterYenc",
    "GMime.Format",
    "GMime.FormatOptions",
    "GMime.GpgContext",
    "GMime.HeaderRawValueFormatter",
    "GMime.InternetAddressGroup",
    "GMime.InternetAddressMailbox",
    "GMime.MessagePart",
    "GMime.Multipart",
    "GMime.MultipartEncrypted",
    "GMime.MultipartSigned",
    "GMime.NewLineFormat",
    "GMime.ObjectForeachFunc",
    "GMime.OpenPGPData",
    "GMime.OpenPGPMarker",
    "GMime.OpenPGPState",
    "GMime.Param",
    "GMime.ParamEncodingMethod",
    "GMime.ParamList",
    "GMime.ParserWarning",
    "GMime.Part",
    "GMime.PartIter",
    "GMime.Pkcs7Context",
    "GMime.PubKeyAlgo",
    "GMime.References",
    "GMime.RfcComplianceMode",
    "GMime.SecureMimeType",
    "GMime.SeekWhence",
    "GMime.Signature",
    "GMime.SignatureList",
    "GMime.SignatureStatus",
    "GMime.Stream",
    "GMime.StreamBuffer",
    "GMime.StreamBufferMode",
    "GMime.StreamCat",
    "GMime.StreamFile",
    "GMime.StreamFilter",
    "GMime.StreamFs",
    "GMime.StreamGIO",
    "GMime.StreamIOVector",
    "GMime.StreamMem",
    "GMime.StreamMmap",
    "GMime.StreamNull",
    "GMime.StreamPipe",
    "GMime.TextPart",
    "GMime.Trust",
    "GMime.UrlScanner",
    "GMime.Validity",
    "GMime.VerifyFlags",
    # "GMime.FilterChecksum",
    #"GMime.ApplicationPkcs7Mime",
]

manual = [
    "GLib.Bytes",
    "GLib.ByteArray",
    "GLib.String",
    "GLib.Error",
    "GLib.Variant",
    "GLib.VariantType",
    "GLib.IOCondition",
    "GLib.SeekType",
    "GLib.Source",
    "GLib.Priority",
    "GLib.DateTime",
    "GLib.ChecksumType",
    "Gio.File",
    "GMime.Message", # partial_split_message has wrong annotations
    "GMime.MessagePartial", # reconstruct_message has wrong annotations
    "GMime.DigestAlgo", # enum items start with digit
    "GMime.ContentEncoding",  # enum items start with digit
    "GMime.EncodingConstraint",  # enum items start with digit
    "GMime.ParserOptions" # incompatibel function definition

    # "GMime.CryptoContextNewFunc",
    # "GMime.ParserHeaderRegexFunc",
    # "GMime.ParserWarningFunc"
]



[[object]]
name = "GMime.ApplicationPkcs7Mime"
status = "generate"

    [[object.function]]
    # wrong array definition
    name = "decrypt"
    ignore = true


[[object]]
name = "GMime.AutocryptHeader"
status = "generate"

    [[object.function]]
    name = "compare"
    # conflicting implementations
    ignore = true

[[object]]
name = "GMime.ContentDisposition"
status = "generate"
    [[object.function]]
    pattern = "(encode|parse)"
        [[object.function.parameter]]
        # optional and thus immutable
        name = "options"
        const = true
        nullable = true

[[object]]
name = "GMime.ContentType"
status = "generate"
    [[object.function]]
    pattern = "(encode|parse)"
        [[object.function.parameter]]
        # optional and thus immutable
        name = "options"
        const = true
        nullable = true

[[object]]
name = "GMime.Header"
status = "generate"
    [[object.function]]
    pattern = "(format_.+|write_to_stream|set_value)"
        [[object.function.parameter]]
        # optional and thus immutable
        name = "options"
        const = true
        nullable = true

[[object]]
name = "GMime.HeaderList"
status = "generate"
    [[object.function]]
    pattern = "(to_string|write_to_stream|new)"
        [[object.function.parameter]]
        # optional and thus immutable
        name = "options"
        const = true
        nullable = true

[[object]]
name = "GMime.InternetAddress"
status = "generate"
    [[object.function]]
    name = "to_string"
        [[object.function.parameter]]
        # optional and thus immutable
        name = "options"
        const = true
        nullable = true

[[object]]
name = "GMime.InternetAddressList"
status = "generate"
    [[object.function]]
    pattern = "(to_string|parse)"
        [[object.function.parameter]]
        # optional and thus immutable
        name = "options"
        const = true
        nullable = true

[[object]]
name = "GMime.Object"
status = "generate"
    [[object.function]]
    pattern = "(new|new_type|to_string|write_to_stream|get_headers)"
        [[object.function.parameter]]
        # optional and thus immutable
        name = "options"
        const = true
        nullable = true

[[object]]
name = "GMime.Parser"
status = "generate"
    [[object.function]]
    pattern = "construct_(part|message)"
        [[object.function.parameter]]
        # optional and thus immutable
        name = "options"
        const = true
        nullable = true
