[options]
girs_dir = "gir-files"
library = "GMime"
version = "3.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = false
min_cfg_version = "1.30"

generate = ["GMime.Stream",
            "GMime.StreamFile",
            "GMime.StreamFs",
            "GMime.StreamGIO",
            "GMime.StreamMem",
            "GMime.StreamMmap",
            "GMime.StreamNull",
            "GMime.StreamFilter",
            "GMime.StreamBuffer",
            "GMime.StreamPipe",
            "GMime.StreamCat",
            "GMime.Filter",
            "GMime.FilterBasic",
            "GMime.FilterBest",
            "GMime.FilterCharset",
            "GMime.FilterChecksum",
            "GMime.FilterDos2Unix",
            "GMime.FilterEnriched",
            "GMime.FilterFrom",
            "GMime.FilterGZip",
            "GMime.FilterHTML",
            "GMime.FilterOpenPGP",
            "GMime.FilterSmtpData",
            "GMime.FilterStrip",
            "GMime.FilterUnix2Dos",
            "GMime.FilterWindows",
            "GMime.FilterYenc",
            "GMime.DataWrapper",
            "GMime.HeaderList",
            "GMime.ContentType",
            "GMime.ContentDisposition",
            "GMime.Object",
            "GMime.Message",
            "GMime.Part",
            "GMime.TextPart",
            "GMime.Multipart",
            "GMime.MultipartEncrypted",
            "GMime.MultipartSigned",
            "GMime.ApplicationPkcs7Mime",
            "GMime.MessagePart",
            "GMime.MessagePartial",
            "GMime.PartIter",
            "GMime.ParserOptions",
            "GMime.Parser",
            "GMime.Certificate",
            "GMime.Signature",
            "GMime.SignatureList",
            "GMime.SignatureStatus",
            "GMime.CryptoContext",
            "GMime.GpgContext",
            "GMime.Pkcs7Context",
            "GMime.SecureMimeType",
            "GMime.ParamList",
            ]
