[options]
girs_dir = "gir-files"
library = "GMime"
version = "3.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = false
min_cfg_version = "1.30"

generate = ["GMime.Stream",
            "GMime.StreamFile",
            "GMime.StreamFs",
            "GMime.StreamGIO",
            "GMime.StreamMem",
            "GMime.StreamMmap",
            "GMime.StreamNull",
            "GMime.StreamFilter",
            "GMime.StreamBuffer",
            "GMime.StreamPipe",
            "GMime.StreamCat",
            "GMime.Filter",
            "GMime.FilterBasic",
            "GMime.FilterBest",
            "GMime.FilterCharset",
            # "GMime.FilterChecksum",
            "GMime.FilterDos2Unix",
            "GMime.FilterEnriched",
            "GMime.FilterFrom",
            "GMime.FilterFromMode",
            "GMime.FilterGZip",
            "GMime.FilterGZipMode",
            "GMime.FilterHTML",
            "GMime.FilterOpenPGP",
            "GMime.FilterSmtpData",
            "GMime.FilterStrip",
            "GMime.FilterUnix2Dos",
            "GMime.FilterWindows",
            "GMime.FilterYenc",
            "GMime.FilterBestFlags",
            "GMime.DataWrapper",
            "GMime.Header",
            "GMime.HeaderList",
            "GMime.ContentType",
            "GMime.ContentDisposition",
            "GMime.OpenPGPData",
            "GMime.Object",
            "GMime.ObjectForeachFunc",
            "GMime.MessagePart",
            "GMime.Part",
            "GMime.TextPart",
            "GMime.Multipart",
            "GMime.MultipartEncrypted",
            "GMime.MultipartSigned",
            #"GMime.ApplicationPkcs7Mime",
            "GMime.PartIter",
            #"GMime.ParserOptions",
            "GMime.Parser",
            "GMime.RfcComplianceMode",
            "GMime.Certificate",
            "GMime.CertificateList",
            "GMime.Signature",
            "GMime.SignatureList",
            "GMime.SignatureStatus",
            "GMime.CryptoContext",
            "GMime.GpgContext",
            "GMime.Pkcs7Context",
            "GMime.SecureMimeType",
            "GMime.Param",
            "GMime.ParamEncodingMethod",
            "GMime.ParamList",
            "GMime.InternetAddressList",
            "GMime.InternetAddress",
            "GMime.InternetAddressMailbox",
            "GMime.AddressType",
            "GMime.Format",
            # "GMime.FormatOptions",
            "GMime.EncryptFlags",
            "GMime.DecryptFlags",
            "GMime.VerifyFlags",
            "GMime.DecryptResult",
            "GMime.NewLineFormat",
            "GMime.PubKeyAlgo",
            "GMime.Trust",
            "GMime.Validity",
            "GMime.SeekWhence",
            "GMime.StreamBufferMode",
            # "GMime.AutocryptHeader",
            "GMime.AutocryptHeaderList",
            "GMime.AutocryptPreferEncrypt",

            ]

manual = [
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Variant",
    "GLib.VariantType",
    "GLib.IOCondition",
    "GLib.SeekType",
    "GLib.Source",
    "GLib.Priority",
    "GLib.DateTime",
    "GLib.ChecksumType",
    "Gio.File",
    "GMime.Message", # partial_split_message has wrong annotations
    "GMime.MessagePartial", # reconstruct_message has wrong annotations
    "GMime.DigestAlgo", # enum items start with digit
    "GMime.ContentEncoding",  # enum items start with digit
    "GMime.EncodingConstraint"  # enum items start with digit
    # "GMime.CryptoContextNewFunc",
    # "GMime.ParserHeaderRegexFunc",
    # "GMime.ParserWarningFunc"
]



[[object]]
name = "GMime.ApplicationPkcs7Mime"
status = "generate"

    [[object.function]]
    # wrong array definition
    name = "decrypt"
    ignore = true


[[object]]
name = "GMime.AutocryptHeader"
status = "generate"

    [[object.function]]
    name = "compare"
    # conflicting implementations
    ignore = true
