
[options]
work_mode = "sys"
library = "GMime"
version = "3.0"
min_cfg_version = "2.26"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]

manual = [
    "GMime._GMimeFilterGZipPrivate",
    "GMime._GMimeParserPrivate",
    "GMime._GMimeStreamFilterPrivate",
    "GMime._GMimeFilterPrivate",
    "GMime._UrlScanner"
]
